spring.application.name=error-free-text

spring.datasource.url=jdbc:postgresql://localhost:15432/error_free_text
spring.datasource.username=error_free_text
spring.datasource.password=local_dev_password

spring.jpa.hibernate.ddl-auto=validate
spring.jpa.open-in-view=false

spring.flyway.enabled=true

spring.jackson.deserialization.fail-on-numbers-for-enums=true
